# Generated by Django 4.2.7 on 2023-12-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='models_ele',
            name='id',
            field=models.IntegerField(default=5),
        ),
    ]
